# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5a218733c79acb9f445c48e52dd0ded35579c63938a2ef6b6da8352eddc297a142323ffc1ccf9da2bbb4bd361e1b2fe37bcfe70c7810a77c127e2bf7c9a76a

test:
  secret_key_base: bf8b77ac76238b931bb8ad3dbcf215c8ee32c3cf1390a6e8933f44c52672f8b7c287dec58839beac78fbfb239d7f8b4e4310a1c2e97a43445ec2fb4d24514b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
